version: '2'
services:
  hub:
    image: silintl/ssp-base:develop
    volumes:
      - ./development/hub/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/hub/saml20-idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php
      - ./development/hub/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./www/default-logo.png:/data/vendor/simplesamlphp/simplesamlphp/www/logo.png
      - ./:/data/vendor/simplesamlphp/simplesamlphp/modules/material
    ports:
      - '80:80'
    environment:
      ADMIN_PASS: "abc123"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      THEME_USE: "material:material"
      HUB_MODE: "true"
      ADMIN_EMAIL: "admin@example.org"
      SECRET_SALT: "FcJwl0zCDc4nuzOuQL9/7WPIj3hdfusGm2ny0dcRQm0="
      IDP_NAME: "The Hub"
      ANALYTICS_ID: "UA-XXXX-Y"
  idp1:
    image: silintl/ssp-base:develop
    volumes:
      - ./development/idp1/cert:/data/vendor/simplesamlphp/simplesamlphp/cert
      - ./development/idp1/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/idp1/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/idp1/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php
    ports:
      - '8085:80'
    environment:
      ADMIN_PASS: "a"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      ADMIN_PROTECT_INDEX_PAGE: "false"
      THEME_USE: "default:default"
      ADMIN_EMAIL: "admin1@example.org"
      SECRET_SALT: "8yC5mb4wqANaU+Rxrl4DHkfKzikeieXkltfFd+YDzx8="
      IDP_NAME: "Idp 1"
  idp2:
    image: silintl/ssp-base:develop
    volumes:
      - ./development/idp2/cert:/data/vendor/simplesamlphp/simplesamlphp/cert
      - ./development/idp2/enable:/data/vendor/simplesamlphp/simplesamlphp/modules/exampleauth/enable
      - ./development/idp2/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/idp2/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/idp2/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php
      - ./www/default-logo.png:/data/vendor/simplesamlphp/simplesamlphp/www/logo.png
      - ./:/data/vendor/simplesamlphp/simplesamlphp/modules/material
    ports:
      - '8086:80'
    environment:
      ADMIN_PASS: "b"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      ADMIN_PROTECT_INDEX_PAGE: "false"
      THEME_USE: "material:material"
      ADMIN_EMAIL: "admin1@example.org"
      SECRET_SALT: "edI4GGkYfkzD6/OXFvHBHb9Meu9hdKXQpNFg4q/GGfY="
      IDP_NAME: "Idp 2"
      ANALYTICS_ID: "UA-XXXX-Y"
      CHANGE_PWD_URL: "http://example.org"
  hub2:
    image: silintl/ssp-base:develop
    volumes:
      - ./development/hub2/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/hub2/saml20-idp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php
      - ./development/hub2/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./www/default-logo.png:/data/vendor/simplesamlphp/simplesamlphp/www/logo.png
      - ./:/data/vendor/simplesamlphp/simplesamlphp/modules/material
      - ./development/idp3/announcement.php:/data/vendor/simplesamlphp/simplesamlphp/announcement/announcement.php
    ports:
      - '8081:80'
    environment:
      ADMIN_PASS: "abc123"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      THEME_USE: "material:material"
      HUB_MODE: "true"
      ADMIN_EMAIL: "admin@example.org"
      SECRET_SALT: "QthhmKnsmC7X/+2bv3CgzBWaFR68J3fP6QgmZhM1L7M="
      IDP_NAME: "The Hub2"
  idp3:
    image: silintl/ssp-base:develop
    volumes:
      - ./development/idp3/cert:/data/vendor/simplesamlphp/simplesamlphp/cert
      - ./development/idp3/authsources.php:/data/vendor/simplesamlphp/simplesamlphp/config/authsources.php
      - ./development/idp3/saml20-idp-hosted.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./development/idp3/saml20-sp-remote.php:/data/vendor/simplesamlphp/simplesamlphp/metadata/saml20-sp-remote.php
      - ./www/default-logo.png:/data/vendor/simplesamlphp/simplesamlphp/www/logo.png
      - ./:/data/vendor/simplesamlphp/simplesamlphp/modules/material
      - ./development/idp3/announcement.php:/data/vendor/simplesamlphp/simplesamlphp/announcement/announcement.php
    ports:
      - '8087:80'
    environment:
      ADMIN_PASS: "a"
      SECURE_COOKIE: "false"
      SHOW_SAML_ERRORS: "true"
      ADMIN_PROTECT_INDEX_PAGE: "false"
      THEME_USE: "material:material"
      ADMIN_EMAIL: "admin1@example.org"
      SECRET_SALT: "xbcCMIHHzsgE8yYC6OIBjsp+ruZYghHn1k5Bv/IGbrg="
      IDP_NAME: "Idp 3"
